// Roles fijos del sistema (Fase 1). Los IDs coinciden con el seed.
const ROLES = Object.freeze({
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  INVENTARIO: 'INVENTARIO',
  USUARIO: 'USUARIO'
});

// Acciones auditables (sección 19 del spec). Se irán ampliando en fases siguientes.
const AUDIT_ACTIONS = Object.freeze({
  LOGIN: 'LOGIN',
  LOGIN_FALLIDO: 'LOGIN_FALLIDO',
  LOGOUT: 'LOGOUT',
  CREAR_USUARIO: 'CREAR_USUARIO',
  MODIFICAR_USUARIO: 'MODIFICAR_USUARIO',
  CREAR_SEDE: 'CREAR_SEDE',
  CREAR_MEDICAMENTO: 'CREAR_MEDICAMENTO',
  MODIFICAR_MEDICAMENTO: 'MODIFICAR_MEDICAMENTO',
  CREAR_LOTE: 'CREAR_LOTE',
  AJUSTAR_LOTE: 'AJUSTAR_LOTE',
  BLOQUEAR_LOTE: 'BLOQUEAR_LOTE',
  CREAR_ORDEN: 'CREAR_ORDEN',
  CONFIRMAR_ORDEN: 'CONFIRMAR_ORDEN',
  CANCELAR_ORDEN: 'CANCELAR_ORDEN',
  DESPACHAR_MEDICAMENTO: 'DESPACHAR_MEDICAMENTO',
  CREAR_ENTREGA: 'CREAR_ENTREGA',
  REGISTRAR_FIRMA: 'REGISTRAR_FIRMA',
  REGISTRAR_HUELLA: 'REGISTRAR_HUELLA',
  CREAR_RESPALDO: 'CREAR_RESPALDO',
  RESTAURAR_RESPALDO: 'RESTAURAR_RESPALDO',
  SOLICITAR_ELIMINACION: 'SOLICITAR_ELIMINACION',
  APROBAR_ELIMINACION: 'APROBAR_ELIMINACION',
  RECHAZAR_ELIMINACION: 'RECHAZAR_ELIMINACION'
});

const ESTADOS_REGISTRO = Object.freeze({
  ACTIVO: 'ACTIVO',
  INACTIVO: 'INACTIVO'
});

module.exports = { ROLES, AUDIT_ACTIONS, ESTADOS_REGISTRO };
