// Roles fijos del sistema (Fase 1). Los IDs coinciden con el seed.
const ROLES = Object.freeze({
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  INVENTARIO: 'INVENTARIO',
  USUARIO: 'USUARIO'
});

// Acciones auditables (sección 19 del spec). Se irán ampliando en fases siguientes.
const AUDIT_ACTIONS = Object.freeze({
  LOGIN: 'LOGIN',
  LOGIN_FALLIDO: 'LOGIN_FALLIDO',
  LOGOUT: 'LOGOUT',
  CREAR_USUARIO: 'CREAR_USUARIO',
  MODIFICAR_USUARIO: 'MODIFICAR_USUARIO',
  ELIMINAR_USUARIO: 'ELIMINAR_USUARIO',
  CREAR_SEDE: 'CREAR_SEDE',
  CREAR_MEDICAMENTO: 'CREAR_MEDICAMENTO',
  MODIFICAR_MEDICAMENTO: 'MODIFICAR_MEDICAMENTO',
  CREAR_LOTE: 'CREAR_LOTE',
  AJUSTAR_LOTE: 'AJUSTAR_LOTE',
  BLOQUEAR_LOTE: 'BLOQUEAR_LOTE',
  CREAR_ORDEN: 'CREAR_ORDEN',
  CONFIRMAR_ORDEN: 'CONFIRMAR_ORDEN',
  CANCELAR_ORDEN: 'CANCELAR_ORDEN',
  DESPACHAR_MEDICAMENTO: 'DESPACHAR_MEDICAMENTO',
  CREAR_ENTREGA: 'CREAR_ENTREGA',
  REGISTRAR_FIRMA: 'REGISTRAR_FIRMA',
  REGISTRAR_HUELLA: 'REGISTRAR_HUELLA',
  CREAR_RESPALDO: 'CREAR_RESPALDO',
  RESTAURAR_RESPALDO: 'RESTAURAR_RESPALDO',
  ACTUALIZAR_CONFIG: 'ACTUALIZAR_CONFIG',
  SOLICITAR_ELIMINACION: 'SOLICITAR_ELIMINACION',
  APROBAR_ELIMINACION: 'APROBAR_ELIMINACION',
  RECHAZAR_ELIMINACION: 'RECHAZAR_ELIMINACION',
  SOLICITAR_INTERCAMBIO: 'SOLICITAR_INTERCAMBIO',
  APROBAR_INTERCAMBIO: 'APROBAR_INTERCAMBIO',
  RECHAZAR_INTERCAMBIO: 'RECHAZAR_INTERCAMBIO',
  // Catálogo CUM
  CATALOGO_CUM_IMPORTAR: 'CATALOGO_CUM_IMPORTAR',
  CATALOGO_CUM_ACTUALIZAR: 'CATALOGO_CUM_ACTUALIZAR',
  CATALOGO_CUM_MANUAL: 'CATALOGO_CUM_MANUAL',
  CATALOGO_EMPAQUE_CREAR: 'CATALOGO_EMPAQUE_CREAR',
  CATALOGO_EMPAQUE_MODIFICAR: 'CATALOGO_EMPAQUE_MODIFICAR',
  RECEPCION_ESCANEAR: 'RECEPCION_ESCANEAR',
  CATALOGO_CUM_DOCUMENTO: 'CATALOGO_CUM_DOCUMENTO',
});

// ESTADO DE UN USUARIO. ELIMINADO no es un synonym de INACTIVO:
// `eliminarDefinitivo` anonimiza la fila (nombre, username y password_hash) y la
// deja en este estado para conservar el histórico. Como `authService.login` y
// `sessionService.resolverUsuarioDesdeSesion` exigen ACTIVO, anonimizar corta el
// acceso y destruye las sesiones vivas sin necesidad de invalidación explícita.
const ESTADOS_REGISTRO = Object.freeze({
  ACTIVO: 'ACTIVO',
  INACTIVO: 'INACTIVO',
  ELIMINADO: 'ELIMINADO'
});

module.exports = { ROLES, AUDIT_ACTIONS, ESTADOS_REGISTRO };
