export const AUDIT_ACTIONS = Object.freeze({
  LOGIN: 'LOGIN',
  LOGIN_FALLIDO: 'LOGIN_FALLIDO',
  LOGOUT: 'LOGOUT',
  CREAR_USUARIO: 'CREAR_USUARIO',
  MODIFICAR_USUARIO: 'MODIFICAR_USUARIO',
  CREAR_SEDE: 'CREAR_SEDE',
  CREAR_MEDICAMENTO: 'CREAR_MEDICAMENTO',
  MODIFICAR_MEDICAMENTO: 'MODIFICAR_MEDICAMENTO',
  CREAR_LOTE: 'CREAR_LOTE',
  AJUSTAR_LOTE: 'AJUSTAR_LOTE',
  BLOQUEAR_LOTE: 'BLOQUEAR_LOTE',
  CREAR_ORDEN: 'CREAR_ORDEN',
  CONFIRMAR_ORDEN: 'CONFIRMAR_ORDEN',
  CANCELAR_ORDEN: 'CANCELAR_ORDEN',
  DESPACHAR_MEDICAMENTO: 'DESPACHAR_MEDICAMENTO',
  CREAR_ENTREGA: 'CREAR_ENTREGA',
  REGISTRAR_FIRMA: 'REGISTRAR_FIRMA',
  REGISTRAR_HUELLA: 'REGISTRAR_HUELLA',
  CREAR_RESPALDO: 'CREAR_RESPALDO',
  RESTAURAR_RESPALDO: 'RESTAURAR_RESPALDO',
  SOLICITAR_ELIMINACION: 'SOLICITAR_ELIMINACION',
  APROBAR_ELIMINACION: 'APROBAR_ELIMINACION',
  RECHAZAR_ELIMINACION: 'RECHAZAR_ELIMINACION',
  SOLICITAR_INTERCAMBIO: 'SOLICITAR_INTERCAMBIO',
  APROBAR_INTERCAMBIO: 'APROBAR_INTERCAMBIO',
  RECHAZAR_INTERCAMBIO: 'RECHAZAR_INTERCAMBIO',
  CATALOGO_CUM_IMPORTAR: 'CATALOGO_CUM_IMPORTAR',
  CATALOGO_CUM_ACTUALIZAR: 'CATALOGO_CUM_ACTUALIZAR',
  CATALOGO_CUM_MANUAL: 'CATALOGO_CUM_MANUAL',
  CATALOGO_EMPAQUE_CREAR: 'CATALOGO_EMPAQUE_CREAR',
  CATALOGO_EMPAQUE_MODIFICAR: 'CATALOGO_EMPAQUE_MODIFICAR',
  RECEPCION_ESCANEAR: 'RECEPCION_ESCANEAR',
  CATALOGO_CUM_DOCUMENTO: 'CATALOGO_CUM_DOCUMENTO',
  CONFLICTO_SINCRONIZACION: 'CONFLICTO_SINCRONIZACION',
} as const);

export type AuditAction = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];

export const ESTADOS_REGISTRO = Object.freeze({
  ACTIVO: 'ACTIVO',
  INACTIVO: 'INACTIVO',
} as const);

export type EstadoRegistro = typeof ESTADOS_REGISTRO[keyof typeof ESTADOS_REGISTRO];

export const ESTADOS_ORDEN = Object.freeze({
  PENDIENTE: 'PENDIENTE',
  PARCIAL: 'PARCIAL',
  COMPLETADA: 'COMPLETADA',
  CANCELADA: 'CANCELADA',
} as const);

export type EstadoOrden = typeof ESTADOS_ORDEN[keyof typeof ESTADOS_ORDEN];

export const ESTADOS_LOTE = Object.freeze({
  DISPONIBLE: 'DISPONIBLE',
  PROXIMO_VENCER: 'PROXIMO_VENCER',
  VENCIDO: 'VENCIDO',
  AGOTADO: 'AGOTADO',
  DADO_DE_BAJA: 'DADO_DE_BAJA',
} as const);

export type EstadoLote = typeof ESTADOS_LOTE[keyof typeof ESTADOS_LOTE];

export const TIPOS_MOVIMIENTO = Object.freeze({
  ENTRADA: 'ENTRADA',
  SALIDA_ORDEN: 'SALIDA_ORDEN',
  AJUSTE: 'AJUSTE',
} as const);

export type TipoMovimiento = typeof TIPOS_MOVIMIENTO[keyof typeof TIPOS_MOVIMIENTO];

export const TIPOS_DESTINO = Object.freeze({
  LOCAL: 'LOCAL',
  MUNICIPIO_VEREDA: 'MUNICIPIO_VEREDA',
} as const);

export type TipoDestino = typeof TIPOS_DESTINO[keyof typeof TIPOS_DESTINO];