import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';
import type { MD3Theme } from 'react-native-paper';

export const theme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 8,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#2563eb',
    primaryContainer: '#dbeafe',
    secondary: '#059669',
    secondaryContainer: '#d1fae5',
    tertiary: '#dc2626',
    tertiaryContainer: '#fee2e2',
    surface: '#ffffff',
    surfaceVariant: '#f8fafc',
    background: '#f1f5f9',
    error: '#dc2626',
    errorContainer: '#fee2e2',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#1e3a5f',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#064e3b',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#7f1d1d',
    onSurface: '#1e293b',
    onSurfaceVariant: '#475569',
    onBackground: '#1e293b',
    onError: '#ffffff',
    onErrorContainer: '#7f1d1d',
    outline: '#cbd5e1',
    outlineVariant: '#e2e8f0',
    inverseSurface: '#1e293b',
    inverseOnSurface: '#f8fafc',
    inversePrimary: '#93c5fd',
    shadow: '#000000',
    scrim: '#000000',
  },
  fonts: MD3LightTheme.fonts,
};

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  roundness: 8,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#3b82f6',
    primaryContainer: '#1e3a5f',
    secondary: '#10b981',
    secondaryContainer: '#064e3b',
    tertiary: '#ef4444',
    tertiaryContainer: '#7f1d1d',
    surface: '#1e293b',
    surfaceVariant: '#334155',
    background: '#0f172a',
    error: '#ef4444',
    errorContainer: '#7f1d1d',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#dbeafe',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#d1fae5',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#fee2e2',
    onSurface: '#f8fafc',
    onSurfaceVariant: '#cbd5e1',
    onBackground: '#f8fafc',
    onError: '#ffffff',
    onErrorContainer: '#fee2e2',
    outline: '#475569',
    outlineVariant: '#334155',
    inverseSurface: '#f8fafc',
    inverseOnSurface: '#1e293b',
    inversePrimary: '#2563eb',
    shadow: '#000000',
    scrim: '#000000',
  },
};
